### ISSUE TITLE
Cannot push from Windows to Github using token as password

### ISSUE THREAD

**Issue by tesonep** [npasserini/iceberg#1410]
The VM crashes and this is the last thing printed

Assertion failed: t->server.cred, file C:\Users\travis\build\guillep\libgit_build\libgit2\src\transports\winhttp.c, line 1159

**Comment by Ducasse** [comment]
argh
Usually we prefer our bugs.

**Comment by dupriezt** [comment]
I have the same issue

**Comment by astares** [comment]
Same for me, already when I manually add a repo to Iceberg and get asked for credentials

![image](https://user-images.githubusercontent.com/5980033/108748604-10ca1280-753f-11eb-9e75-a3a780f85035.png)

**Comment by astares** [comment]
I guess the reason is not the external library ´- but the implementation of the new Password Dialog:

Try to click on IGNORE on the VisualC++ Runtime failure and then in the Pharo debugger run:

```Smalltalk
IceTipAskForPlaintextCredentialsModel new
		credentialStore: self credentialStore;
		askingHostname: remote host;
		openModalWithSpec;
		credentials.
```
while providing valid credentials:  the **dialog always returns nil**

![image](https://user-images.githubusercontent.com/5980033/108752253-8506b500-7543-11eb-8004-9f7e585497c4.png)

whatever I do the #accept (and also the #acceptAskAction) is never called.

I guess there is a mismatch in what Spec2 provides and what IceTipAskForPlaintextCredentialsModel implements.


Maybe @tinchodias can help here

**Comment by astares** [comment]
maybe the https://github.com/pharo-vcs/iceberg/pull/1428 is related to that too (have not checked)

**Comment by tinchodias** [comment]
I broke it in the migration but should be fine now.
