### ISSUE TITLE
Crash on push - MacOS

### ISSUE THREAD

**Issue by tinchodias** [npasserini/iceberg#1418]
Milton (@akevalion) reported the attached error, only visible in the terminal after crash.

Method in execution was `remote_push_v100:refspecs:opts:`.

[terminal_error.txt](https://github.com/pharo-vcs/iceberg/files/5973877/terminal_error.txt)

**Comment by tinchodias** [comment]
More context:

- P9.0 with Iceberg v2
- it was a SSH remote
- he entered user and password in the credentials dialog that popped (but in previous Pharo 9  this wasn't happening, this means that ssh credentials didn't work well)

So I suspect there that an error callback was executed from libgit and... crash

@tesonep @guillep you know more of this ;)

**Comment by guillep** [comment]
If it is an ssh remote and the dialog asking for user/pass popped-up, it means SSH did not work (not the other way around).
I'd say that ssh used to work in the previous version and not in this one?

I have seen a problem similar in previous versions with callbacks and dialogs.
Libgit calls a callback on iceberg to ask for credentials, iceberg should open a dialog in this case to ask for user/pass but **not return** the control to libgit. That is, it should not return the callback. Otherwise when accepting the dialog it will try to call some libgit functions to manage the callback, but the function activating the callback has already returned...
