### ISSUE TITLE
Cannot save code!!! And can reproduce it in p9-beta

### ISSUE THREAD

**Issue by Ducasse** [npasserini/iceberg#1500]
- Rename MicroDownParser to MicrodownParser
- Save 
- All the changes are saved except the renaming.

**Comment by tesonep** [comment]
The problem is in OSX when using case insensitive file system (the default).

I could reproduce it, as @guillep  said it is a casing problem.
If I delete the file in the working copy before committing, it works

The problem is that we are passing through the disk....
Maybe... when we calculate a delete in a class we need to force the deletion in the disk (we are just exporting the whole package using Tonel)

**Comment by Ducasse** [comment]
Ah of course.

**Comment by Ducasse** [comment]
of course mac is not case sensitive.

**Comment by MarcusDenker** [comment]
So I guess this is not a bug to be fixed
