### ISSUE TITLE
Option to commit to local repository

### ISSUE THREAD

**Issue by dolezvo1** [npasserini/iceberg#1832]
As the title says, I'd really appreciate an option to commit to the source local repository. I'm really not sure of the reason why this doesn't seem to be easily possible. This fact is especially inconvenient when your project contains non-Smalltalk files that you have workflows built around.

**Comment by dolezvo1** [comment]
These are the options that I see on the local repository:

![image](https://github.com/user-attachments/assets/1ede524d-0d0c-4363-a580-0e4a4c89e5fc)

Meanwhile on the other repositories I see all these other options:

![image](https://github.com/user-attachments/assets/45684c5d-79c5-4e07-931c-c03ba1b150c7)

**Comment by dolezvo1** [comment]
I should also mention that Iceberg doesn't seem to be able to find my SSH keys, which points to it probably not being able to parse the host+key definitions in the home directory which git uses, so that's another use case for you.

**Comment by Ducasse** [comment]
Thanks for your report. 
Please open a separate issue for your ssh keys. 
Now you should consider 
- you should provide more information because like that we cannot do much (which OS, which version of Pharo)
- you should see that we all use SSH to connect to github and others. So we need to know what is not working, if you tested your connection on the command line (without Pharo in the middle, if you are running an ssh-agent and how).

**Comment by dolezvo1** [comment]
Sorry, but I'm not interested in Pharo/Iceberg touching my SSH keys, so I will not be creating the issue.

**Comment by Ducasse** [comment]
This is not touching this is using your ssh keys. 
How do you want git to work if it cannot pass to libgit your ssh keys :)?
Apparently you misunderstand something important but you have the right to do so.

**Comment by Ducasse** [comment]
OK so I will close this issue. To be able to help we need more collaboration.

**Comment by dolezvo1** [comment]
>Apparently you misunderstand something important but you have the right to do so.

No, I really don't believe so. Pharo/Iceberg doesn't need to touch my keys to commit to a local repository, as far as my understanding goes.

**Comment by tinchodias** [comment]
@dolezvo1 after you select the "Repair repository" option in the menu, these options appear (Pharo 13 colors):

<img width="583" alt="Screenshot 2024-07-22 at 16 00 52" src="https://github.com/user-attachments/assets/ba84f272-5f09-4930-8f9c-b76655fef544">

then a window like this popups:

<img width="678" alt="Screenshot 2024-07-22 at 16 06 14" src="https://github.com/user-attachments/assets/c7143cbb-a6df-4ce0-9ce7-fce5eff7ef64">

What did I do? in this case, what is shown are changes that I did on my local repo (my clone):
1 - in a terminal, I removed the "sdfg..." file
2 - code was modified externally
3 - commit from the terminal (I didn't push)
4 - I came back to Pharo IDE and Iceberg showed the "Detached Working Copy" because the head of the local repo is different than the head that Iceberg knew. That's why Iceberg considers a "repair" is needed... because for Iceberg, the head of that repo was X, but suddenly it finds that head is Y.

I was not very structured on this answer, but I hope it helps.
