### ISSUE TITLE
Question: Is it possible to load a project throught Iceberg GUI?

### ISSUE THREAD

**Issue by jecisc** [npasserini/iceberg#184]
Here is the user case:
- I want to work on my project. 
- I open a new image.
- I load Iceberg. 
- I want to import my project so I open iceberg and add a local repository. 
- In this repository nothing is loaded. 

What I can expect is to right click on the (or one a the) baseline package(s) and get an option "load project". 

Is it possible? If not, is it on the roadmap? If not, do you thing it should be one of Iceberg responsibility?

**Comment by guillep** [comment]
Loading a project is not iceberg's responsibility but metacello's.

That said, I would expect such a thing to be loaded as a plugin. Mainly to keep modularity. But then:

 - what would be a plugin architecture for iceberg('s UI)?
 - who would propose to write such a plugin? :)

**Comment by dalehenrich** [comment]
@npasserini ... I tried to talk about this at ESUT, but I really think that you guys need a project oriented dashboard similar to what you've done for the CatalogBrowser but for loaded projects ... Metacello is programming API not a tool and there should be a project-oreient tool in pharo that wraps the Metacello project with a Pharo project ... I think that this heavy emphasis on packages is completely wrong ... with git-based projects developers should be thinking in terms of projects not packages ... do C developers fret over compiling each individual C file in their project? No, of course not, they *build the project* a package is no more than a C source file in a **project** ...

There **is** or **should be** a one-to-one mapping between a git repository and a Metacello project, so it is natural to imagine that the pharo tool designed to manage the git repository would also be aware of the Metacello project ... but instead the pharo tool for the git repository is only managing the individual trees instead of the forest ..

**Comment by npasserini** [comment]
@dalehenrich there is a one-to-one mapping between a git repository and a Metacello project.

@jecisc The problem is that a Metacello project / git repository normally consists of a lot of packages, so Iceberg does not know which packages to load. 

So right now you have two possibilities:
1) If you first install Iceberg and then try to load a project using Metacello and a github:// URL, by default it will use Iceberg and you will get what you want. We have to see some details with Dale, but I think that this should be the usual way to load a project.
2) Another possibility is to create the repository and then load the packages one by one.

I do not think that we should incorporate into Iceberg all the logic which is necessary to select which packages to load, nor to read a Metacello baseline or create our own "baselines". Metacello is already there for that.

So what I could do is just add an option to load *all* packages in the repository, that's easy but I am not sure if it would be useful.

**Comment by npasserini** [comment]
I am closing this for now, but I am open to listen to further opinions.

**Comment by jecisc** [comment]
My idea was to have a context menu entry to launch the Metacello command. Not duplicate the logic so that Iceberg can load it. Because it's boring to have to type the Metacello script each time. As Dale said, Metacello is here to get the logic and we should have a GUI to interact with it. I though it would be cool to have this in Iceberg but maybe this would be another project.
 
And it was definitively not to load package by package because you do not bring dependencies :)

**Comment by dalehenrich** [comment]
@npasserini I agree with @jecisc ... this is what I am mean when I talk about being project-centric ... If  it isn't appropriate for IceBerg to load and manage Metacello projects, then you certainly need a tool that does ...

**Comment by npasserini** [comment]
@jecisc @dalehenrich I would like to hear more about your ideas for this issue. 
First I would like to imagine the flow, should I execute a Metacello script when you first create/import a repository or should we first create the repo and then execute scripts on it?

But then real problems begin, because I am not sure that we can create Metacello scripts automatically. So my basic metacello script looks like this:

```
Metacello new baseline: 'Iceberg'; repository: '....'; load: #development.
```

The repository argument has (at least) two parts: a github:// url and a commitish (tag, branch or SHA). So, what can be easily be done is to create a Dialog in which you provide the four needed arguments (baseline, url, commitish and what to load). If you do this on an already existing repository you can avoid asking for the URL. If you do it without an existing repository, we should think if we want to use the github:// url style as currently Metacello does or the standard github urls such as git@github.com:npasserini/iceberg.git (or they equivalent for bitbucket/gitlab).

Is that more or less what you have in mind?

**Comment by jecisc** [comment]
Hi!

In my opinion we should have the option (not an obligation) to load the project when we create/import the project.

Else, yes, for me, this is approximately what I have in mind :)

Should this issue be reopened?

**Comment by npasserini** [comment]
@dalehenrich what do you think?
