### ISSUE TITLE
When adding a new package, the dirty packages are not always at the top of the list

### ISSUE THREAD

**Issue by jecisc** [npasserini/iceberg#622]
**OS:** Windows 10

**Pharo:** #60540

**Iceberg version:** v0.7.1

**What I did:**

I created a new class in a new package and I wanted to add it to one of my project. After clicking on "Add package" I got the list of the package. I expected the dirty packages to be at the top but the list was only alphabeticaly sorted. 

See:

![2018-04-11_11-11-43](https://user-images.githubusercontent.com/9519971/38607932-439d86ec-3d7a-11e8-9b65-31643d6a2fba.gif)

**Comment by estebanlm** [comment]
think is... dirty does not means anything now before a package is in repository, now. 
Because a package can be in a repository X and be dirty there and in a repository Y and be clean there. 
what you see as dirty is "dirty in monticello", which does not has sense anymore (and in fact, I think tools should not take more that into account).
